version: '3'

services:
  nginx:
    build:
      context: ./poko/nginx  # 빌드 컨텍스트가 위치한 디렉토리
      args:
        - NGINX_CONF=nginx.prod.conf
    volumes:
      - ./frontend/build:/usr/share/nginx/html   # 로컬에서 빌드된 프론트엔드 파일을 Nginx 컨테이너로 마운트(중요)
      - static_volume_v2:/usr/src/app/static
      - media_volume_v2:/usr/src/app/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  web:
    build:
      context: ./poko
    command: gunicorn poko.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_v2:/usr/src/app/static
      - media_volume_v2:/usr/src/app/media
      - ./poko:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./poko/env/.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data/
    env_file:
      - ./poko/env/.env.prod.db

volumes:
  postgres_data_v2:
  static_volume_v2:
  media_volume_v2: