# Generated by Django 5.0.6 on 2024-09-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="attendance.member",
                to_field="name",
            ),
        ),
    ]
