# Generated by Django 5.0.6 on 2025-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_attendance_alter_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, help_text="학생 생년월일", null=True),
        ),
    ]
