# Generated by Django 5.0.6 on 2026-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_member_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("name", "date"), name="uniq_attendance_member_date"
            ),
        ),
    ]
