# Generated by Django 5.0.6 on 2024-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
