# Generated by Django 5.0.6 on 2025-01-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="kakao_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
