# Generated by Django 5.0.6 on 2025-02-15 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_kakao_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="head_teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "HEAD"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistance_teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("HEAD", "정교사"), ("ASSISTANT", "부교사")],
                default="ASSISTANT",
                max_length=10,
            ),
        ),
    ]
