# Generated by Django 5.0.6 on 2025-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_head_teacher_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="class_name",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
