# Generated by Django 5.0.6 on 2024-07-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GetImage",
        ),
    ]
