# Generated by Django 5.0.6 on 2024-09-09 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gqs",
                    models.BooleanField(
                        choices=[(False, "불참"), (True, "참석")], default=True
                    ),
                ),
                (
                    "pray_member",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_sunday", models.DateField(blank=True, null=True)),
                ("week_number", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "작성중"), (1, "작성완료")],
                        default="0",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membercheck",
                        to="attendance.member",
                        to_field="name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=500)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="report.membercheck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=30, null=True)),
                (
                    "worship",
                    models.IntegerField(
                        choices=[
                            (0, "불참"),
                            (1, "1부 예배"),
                            (2, "2부 예배"),
                            (3, "3부 예배"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "qt",
                    models.IntegerField(
                        choices=[
                            (0, "0회"),
                            (1, "1회"),
                            (2, "2회"),
                            (3, "3회"),
                            (4, "4회"),
                            (5, "5회"),
                            (6, "6회"),
                            (7, "7회"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "pray",
                    models.IntegerField(
                        choices=[
                            (0, "0회"),
                            (1, "1회"),
                            (2, "2회"),
                            (3, "3회"),
                            (4, "4회"),
                            (5, "5회"),
                            (6, "6회"),
                            (7, "7회"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "meeting",
                    models.BooleanField(
                        choices=[(False, "불참"), (True, "참석")], default=True
                    ),
                ),
                (
                    "pray_Dept",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_group",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_user",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_emergency",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("issue", models.CharField(default=None, max_length=300, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_sunday", models.DateField(blank=True, null=True)),
                ("week_number", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "작성중"), (1, "작성완료")],
                        default="0",
                        max_length=50,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usercheck",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
