# Generated by Django 5.0.6 on 2025-05-01 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_usercheck_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pray_Dept",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_group",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_user",
                    models.CharField(default=None, max_length=300, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="membercheck",
            old_name="name",
            new_name="member_name",
        ),
        migrations.RemoveField(
            model_name="membercheck",
            name="gqs",
        ),
        migrations.RemoveField(
            model_name="membercheck",
            name="pray_member",
        ),
        migrations.RemoveField(
            model_name="usercheck",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="usercheck",
            name="pray_Dept",
        ),
        migrations.RemoveField(
            model_name="usercheck",
            name="pray_emergency",
        ),
        migrations.RemoveField(
            model_name="usercheck",
            name="pray_group",
        ),
        migrations.RemoveField(
            model_name="usercheck",
            name="pray_user",
        ),
        migrations.AddField(
            model_name="membercheck",
            name="care_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membercheck",
            name="gqs_attendance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membercheck",
            name="issue",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="membercheck",
            name="user_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.usercheck",
            ),
        ),
        migrations.AlterField(
            model_name="membercheck",
            name="status",
            field=models.IntegerField(
                choices=[(0, "작성중"), (1, "작성완료")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="status",
            field=models.IntegerField(
                choices=[(0, "작성중"), (1, "작성완료")], default=0
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=500)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "member_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="report.membercheck",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
