# Generated by Django 5.0.6 on 2025-05-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_pray_rename_name_membercheck_member_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membercheck",
            old_name="member_name",
            new_name="member",
        ),
        migrations.RenameField(
            model_name="pray",
            old_name="pray_Dept",
            new_name="pray_dept",
        ),
        migrations.RenameField(
            model_name="pray",
            old_name="pray_user",
            new_name="pray_teacher",
        ),
        migrations.RenameField(
            model_name="usercheck",
            old_name="meeting",
            new_name="meeting_attendance",
        ),
        migrations.RenameField(
            model_name="usercheck",
            old_name="pray",
            new_name="pray_count",
        ),
        migrations.RenameField(
            model_name="usercheck",
            old_name="qt",
            new_name="qt_count",
        ),
        migrations.RenameField(
            model_name="usercheck",
            old_name="worship",
            new_name="worship_attendance",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="member_check",
        ),
        migrations.AddField(
            model_name="feedback",
            name="user_check",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="report.usercheck",
            ),
        ),
        migrations.AddField(
            model_name="pray",
            name="user_check",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.usercheck",
            ),
        ),
    ]
