# Generated by Django 5.0.6 on 2025-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_rename_member_name_membercheck_member_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membercheck",
            name="issue",
        ),
        migrations.AddField(
            model_name="usercheck",
            name="issue",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
