# Generated by Django 5.0.6 on 2025-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_remove_membercheck_issue_usercheck_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercheck",
            name="issue",
            field=models.TextField(default=None, null=True),
        ),
    ]
