# Generated by Django 5.0.6 on 2025-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_alter_usercheck_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercheck",
            name="meeting_attendance",
            field=models.BooleanField(
                choices=[(False, "불참"), (True, "참석")], default=True, null=True
            ),
        ),
    ]
