# Generated by Django 5.0.6 on 2025-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_alter_usercheck_meeting_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercheck",
            name="status",
            field=models.IntegerField(
                choices=[(0, "작성중"), (1, "작성완료"), (2, "답변완료")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="status",
            field=models.IntegerField(
                choices=[(0, "작성중"), (1, "작성완료"), (2, "답변완료")], default=0
            ),
        ),
    ]
