# Generated by Django 5.0.6 on 2025-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_alter_membercheck_status_alter_usercheck_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(),
        ),
    ]
