# Generated by Django 5.0.6 on 2025-12-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0010_alter_feedback_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pray",
            name="pray_dept",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="pray",
            name="pray_group",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="pray",
            name="pray_teacher",
            field=models.TextField(default=None, null=True),
        ),
    ]
